name: "Upload Windows DLLs"

on:
  pull_request:
    branches:
      - "master"
  release:
    types: [ published ]

jobs:
  windows-release-build:
    strategy:
      fail-fast: false
      matrix:
        version: [ "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3" ]
        arch: [ x64, x86 ]
        ts: [ ts, nts ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download DLL
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: windows-tests.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          # Note: keep this in sync with the uploaded artifact name in windows-tests.yml
          name: php_solr-dll-${{ matrix.version }}-${{ matrix.ts }}-${{ matrix.arch }}-${{ github.sha }}
      - name: Create and attach release archive
        run: |
          ARCHIVE=php_solr-dll-${{ matrix.version }}-${{ matrix.ts }}-${{ matrix.arch }}-${{ github.ref_name }}.zip
          zip $ARCHIVE php_solr.dll CREDITS LICENSE README.md
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: php_solr-dll-${{ matrix.version }}-${{ matrix.ts }}-${{ matrix.arch }}-${{ github.ref_name }}.zip
          overwrite: true
