name: "Upload Windows DLLs"

on:
  pull_request:
    branches:
      - "master"
  release:
    types: [published]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        arch: [x64, x86]
        ts: [ts, nts]
    steps:
      - name: Download DLL
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: windows-tests.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: php_solr-dll-${{ matrix.version }}-${{ matrix.ts }}-${{ matrix.arch }}-${{ github.sha }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: php_solr.dll
          asset_name: php_solr-dll-${{ matrix.version }}-${{ matrix.ts }}-${{ matrix.arch }}.dll
          tag: ${{ github.ref }}
